### ISSUE TITLE
Make something to collect email addresses

### ISSUE THREAD

**Issue by pastorryanhayden** [SitesForChurch/sitesforchurch-website#1]
On the coming-soon page there is a simple one input form for collecting the email addresses of those who are interested in SitesForChurch.  Can you build (or direct me what to do) something to dump those email addresses in a database?

**Comment by Codenator81** [comment]
I think we need plugin with component. Like contactDB. Where we can see list of contacts after save.

**Comment by pastorryanhayden** [comment]
Figured it out.  Used https://octobercms.com/plugin/jorgeandrade-subscribe
